import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import MainNavbar from "./components/Navbar";
import Footer from "./components/Footer";
import ScrollToTopButton from "./components/ScrollToTopButton"; 
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${poppins.variable} antialiased relative`}>
        <header className="bg-white/96 sticky top-0 z-10 py-4">
          <MainNavbar />
        </header>
        <main className="min-h-[calc(100vh-370px)]">
          {children}
        </main>
        <footer>
          <Footer />
        </footer>

        {/* ✅ Scroll to Top button */}
        <ScrollToTopButton />
      </body>
    </html>
  );
}
